### ISSUE TITLE
GOVNO Ты

### ISSUE THREAD

**Issue by sonic1233** [NobleFox/noblefox.github.io#4]
Mnje enfavitsa

**Comment by sonic1233** [comment]
I dont like everythuung

**Comment by NobleFox** [comment]
![image](https://user-images.githubusercontent.com/32613674/36631869-ac01680a-1987-11e8-8e73-761003228f09.png)

**Comment by NobleFox** [comment]
fixed

**Comment by NobleFox** [comment]
fixed

**Comment by sonic1233** [comment]
![image](https://user-images.githubusercontent.com/28726000/36631876-be11691e-1987-11e8-81d6-a9cadf7b839c.png)
